name = "advent_of_code"
version = "0.1.0"
gleam = "~> 1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.36.0"
gleam_json = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
gladvent = "~> 0.7"
