name: Test

on:
  push:
  pull_request:

jobs:
  test:
    uses: TanklesXL/gleam_actions/.github/workflows/test.yaml@main
    with:
      gleam_version: 1.8.0
      test_node: false
      test_erlang: false
